name: "CodeSniffer"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  codesniffer:
    name: "CodeSniffer"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          ini-values: memory_limit=-1

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Code Sniffer"
        run: "vendor/bin/phpcs --standard=PSR2 ./src ./tests/AssetManagerTest"
